baseURL = "https://TFRMR.github.io/lab-tofarmer/"
languageCode = "id-id"
title = "ToFarmer"

# --- PERBAIKAN KRUSIAL DISINI ---
canonifyURLs = true           # Ubah jadi true agar Hugo otomatis memperbaiki path link
relativeURLs = true           # Tambahkan ini agar semua link bersifat relatif terhadap posisi file
# --------------------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

publishDir = "docs"